# Generated by Django 4.0.3 on 2022-03-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contact_gallery_newsletter_delete_subscribedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
