# Generated by Django 4.0.3 on 2022-03-16 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_gallery_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.IntegerField(null=True)),
                ('Month', models.CharField(max_length=128, null=True)),
                ('from_time', models.TimeField(null=True)),
                ('to_time', models.TimeField(null=True)),
                ('place', models.CharField(max_length=128, null=True)),
                ('title', models.CharField(max_length=128, null=True)),
                ('description', models.TextField(null=True)),
                ('img', models.ImageField(upload_to='event/')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Event',
            },
        ),
    ]
