# Generated by Django 4.0.3 on 2022-03-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('main_title', models.CharField(max_length=120, null=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='slider/%y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
    ]
